/home/luc/hgwork/faggio/docs/api/lino_faggio.settings.test.rst:4: WARNING: autodoc: failed to import module u'lino_faggio.settings.test'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luc/repositories/sphinx/sphinx/ext/autodoc.py", line 367, in import_object
    __import__(self.modname)
ImportError: No module named test
